'use strict';

describe('Testing provider: ParseBackend', function () {
    var $q, ParseBackend;
    ParseBackend = null;
    $q = null;

    beforeEach(module('module.ParseBackend', function (ParseBackendProvider) {
        ParseBackendProvider.setApplicationId('2Jj90cq6pWcVAVGJfTBFmZRicOYlcANheJ2UoIYm');
        ParseBackendProvider.setJavascriptKey('nPD4gFB5zzkzDQHv5YMbYHz0SIKssbPUWp7X3LRX');
    }));

    beforeEach(inject(function (_ParseBackend_, _$q_) {
        ParseBackend = _ParseBackend_;
        $q = _$q_;
    }));

    it('should create a parse object', function () {
        var Account, account;
        Account = ParseBackend.Object.extend("Account");

        account = new Account();
        account.set("access_token", "test_token");

        //var test = account.save();
        var test = account.save().then(function (rec) {
            var test = "test";
        }).catch(function (err) {
            var err = 'error';
        });


    });
});

// ---
// generated by coffee-script 1.9.2